### ISSUE TITLE
Theme Menu – Symbols

### ISSUE THREAD

**Issue by SeverinJB** [mxtxt/mxtxt.github.io#14]
_Situation:_
The menu buttons currently persist of numbers or the 'X'.
 
_Task:_
- [x] Search for symbols 
- [x] Place symbols within the HTML doc
- [x] Assure symbols are displayed correctly on mobile

**Comment by SeverinJB** [comment]
For my themes 'Art Deco' and 'Futurama' I would like to use one of the symbols shown in the .jpg below and [Bender](https://en.wikipedia.org/wiki/Bender_(Futurama)) from the TV series "Futurama". 

![CS-967-12-21cm-Futurama-bender-funny-car-sticker-vinyl-decal-silver-black-for-auto-car jpg](https://user-images.githubusercontent.com/32867365/56137913-0da28a80-5f96-11e9-8831-26cc404ccb0f.png)
![500_F_167222659_9lXyuyC0VBsoERH6cWeyZqYryqVoqwhp](https://user-images.githubusercontent.com/32867365/56137921-0ed3b780-5f96-11e9-9c35-fdd8cde63edc.jpg)

**Comment by delfimpandiani** [comment]
for Victorian Playbill


![27f5992f9a50a89fe83fc4d49ee65342](https://user-images.githubusercontent.com/44606644/56146754-15b6f600-5fa7-11e9-8ac2-15cfa33031ab.png)
![56432441-theater-acting-vector-black-icons-acting-theater-mask-theater-icon-theater-comedy-art-drama-theater-](https://user-images.githubusercontent.com/44606644/56146758-18195000-5fa7-11e9-9eb9-a42ffb75aa6b.jpg)
